# Sensor Telemetry Service configuration

# Logging (debug, error, warn, info)
log-level: debug

# Prometheus metrics server port
prometheus-port: 3301

# MQTT broker connection
mqtt-broker-ip-address: "10.10.10.64"
mqtt-topic-telemetry: "iot/telemetry"

# Optional: Prometheus source label sanitization
sensor-source-max-length: 30
sensor-source-valid-chars-regex: "a-zA-Z0-9._-"
