# Sensor Telemetry Services configuration

# Logging (debug, error, warn, info)
logLevel: debug

# API server port
apiPort: 3301

# MQTT broker connection
mqttBrokerIpAddress: 10.10.10.64
mqttTopicTelemetry: iot/v2/telemetry
mqttTopicLog: iot/v2/log

# Optional: Prometheus source label sanitization
sensorSourceMaxLength: 30
sensorSourceValidCharsRegex: a-zA-Z0-9._-

# Forward sensor logs to application logger
forwardSensorLogs: true
forwardSensorLogsLevel: info
