/*
 * Copyright (c) 2026 dodson Software ( dodson labs )
 * SPDX-License-Identifier: MIT
 */

// **** Common

/**
 * Untrusted JSON object parsed from an MQTT payload.
 *
 * Field names and values come from sensor firmware, so the document is
 * treated as opaque: reads go through the field helpers in
 * SystemFunctions/MqttNetworking, which validate each value per field.
 */
export type JsonObject = Record<string, unknown>;

/**
 * Type guard for JsonObject. JSON.parse of a well-formed body can still
 * yield an array or a primitive, which the handlers cannot index, so
 * on_message narrows once and every handler receives a JsonObject.
 */
export function isJsonObject(value: unknown): value is JsonObject {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

export interface SystemInfo {
  key: string;
  value: string;
}

export interface IAbout {
  about: {
    name: string;
    version: string;
    author: string;
    copyright: string;
    license: string;
    description: string;
  }
  system_info: SystemInfo[];
}

// **** Logger

/**
 * Supported log levels for the application.
 */
export const enum LogLevel {
  None = 0,
  Debug,
  Info,
  Warn,
  Error,
  Critical,
}

/**
 * Logical category for log entries.
 * Used to classify logs for filtering and routing.
 */
export type LogType = "service" | "sensor" | "audit";

/**
 * Severity level for errors.
 */
export type ErrorSeverity = "standard" | "critical";

/**
 * Metadata attached to log entries.
 */
export interface LogMetadata {
  /**
   * Stable machine-readable event name (snake_case).
   * Examples: configuration_loaded, mqtt_connected, route_not_found
   */
  event?: string;

  /**
   * Logical category of this log entry.
   * - 'service': Internal backend lifecycle and infrastructure
   * - 'sensor': Events generated by or describing a specific sensor
   * - 'audit': State-changing operations initiated by users/admins
   */
  logType?: LogType;

  /**
   * Severity for error-level logs.
   * Use 'critical' only when immediate operator attention is required.
   */
  severity?: ErrorSeverity;

  /**
   * Whether the process cannot safely continue.
   * Required when severity is 'critical'.
   */
  fatal?: boolean;

  /**
   * Non-zero exit code to use if fatal is true.
   * Required when fatal is true.
   */
  exitCode?: number;

  /**
   * Logical module where the log originated.
   * Derived from originator parsing if not provided explicitly.
   */
  module?: string;

  /**
   * Function or method name where the log originated.
   * Derived from originator parsing if not provided explicitly.
   */
  function?: string;

  /**
   * Request correlation ID for HTTP requests.
   */
  requestId?: string;

  /**
   * Command correlation ID for MQTT commands.
   */
  commandId?: string;

  /**
   * Sensor or device source identifier.
   */
  source?: string;

  /**
   * Operation duration in milliseconds.
   */
  durationMs?: number;

  /**
   * Error object to serialize and include in the log.
   */
  error?: unknown;

  /**
   * Additional custom fields.
   */
  [key: string]: unknown;
}

/**
 * Extended metadata for critical errors.
 */
export interface CriticalLogMetadata extends LogMetadata {
  severity: "critical";
  fatal: boolean;
  exitCode?: number;
}

/**
 * Logger interface for structured logging.
 */
export interface ILogger {
  /**
   * Get the current log level as a numeric value.
   */
  global_log_level(): LogLevel;

  /**
   * Get the current log level as a string.
   */
  global_log_level_string(): string;

  /**
   * Write an info-level log entry.
   * @param originator - Module/function identifier (e.g., "module/function")
   * @param message - Human-readable log message
   * @param metadata - Optional structured metadata
   */
  write_info(
    originator: string,
    message: string,
    metadata?: LogMetadata,
  ): void;

  /**
   * Write a warn-level log entry.
   * @param originator - Module/function identifier (e.g., "module/function")
   * @param message - Human-readable log message
   * @param metadata - Optional structured metadata
   */
  write_warn(
    originator: string,
    message: string,
    metadata?: LogMetadata,
  ): void;

  /**
   * Write an error-level log entry (standard severity).
   * @param originator - Module/function identifier (e.g., "module/function")
   * @param message - Human-readable log message
   * @param metadata - Optional structured metadata
   */
  write_error(
    originator: string,
    message: string,
    metadata?: LogMetadata,
  ): void;

  /**
   * Write a critical error-level log entry.
   * Uses Winston's error level with severity: "critical".
   * @param originator - Module/function identifier (e.g., "module/function")
   * @param message - Human-readable log message
   * @param metadata - Critical log metadata including fatal and exitCode
   */
  write_critical(
    originator: string,
    message: string,
    metadata: CriticalLogMetadata,
  ): void;

  /**
   * Write a debug-level log entry.
   * @param originator - Module/function identifier (e.g., "module/function")
   * @param message - Human-readable log message
   * @param metadata - Optional structured metadata
   */
  write_debug(
    originator: string,
    message: string,
    metadata?: LogMetadata,
  ): void;

  /**
   * Update the log level at runtime.
   * @param level - New log level string ("error", "warn", "info", "debug")
   * @returns true if the level was changed, false if invalid
   */
  setLogLevel(level: string): boolean;
}

export interface IMqttNetworking {
  is_connected(): boolean;
  /**
   * True once the broker has acknowledged every configured subscription.
   * Connection alone is not readiness: a broker may grant CONNECT while
   * denying SUBSCRIBE, leaving the client connected but ingesting nothing.
   */
  subscriptions_active(): boolean;
  /** Per-topic subscription state, consumed by the mqtt_subscription_active gauge. */
  get_subscription_states(): Array<{ topic: string; active: boolean }>;
  /**
   * Shut down the MQTT client and the Prometheus HTTP server. timeout_ms is a
   * deadline for the ENTIRE close path (the HTTP drain and the MQTT
   * disconnect share one budget), so callers typed against this interface
   * can bound shutdown the same way index.ts does.
   */
  close(timeout_ms?: number): Promise<void>;
  /** True once the Prometheus HTTP server is listening and can serve /metrics. */
  prometheus_server_ready(): boolean;
}
